### ISSUE TITLE
Guide to set this up?

### ISSUE THREAD

**Issue by JorgeDDW** [panigrah/fat_free_crm#3]
Hi team, im just looking for a guide to set this up.

when i bundle install i get: The path `/Users/jorge/Desktop/Temp/reform-dryv-example/vendor/reform` does not
exist.

**Comment by dan-klasson** [comment]
@JorgeDDW You need to change this line:

https://github.com/panigrah/fat_free_crm/blob/master/Gemfile#L83

**Comment by JorgeDDW** [comment]
With what?

**Comment by dan-klasson** [comment]
With `gem "reform"` or a specific reform version that it works with. Why are you trying to install this? You know it's just a fork and not a finished implementation right?

**Comment by JorgeDDW** [comment]
Im trying to install this because of Rails 5.
Also I want to learn more about Rails 5 and building a custom CRM.
Also that FatFreeCRM team are not working on implementation for Rails 5.

**Comment by dan-klasson** [comment]
Then don't spend anymore time on this fork. It is not what you are looking
for.

**Comment by panigrah** [comment]
@JorgeDDW & @dan-klasson 
I restarted a fork for rails5.0.1 https://github.com/triloch/fat_free_crm. There were significant changes between rails5beta and 5.0 that it was easiest to restart. 90% of the test pass. 10% tests fail. Of these 10% about 10% are real issues, the remaining are due to changes in rspec - so the tests have to be redone.

There are at least 4 gems that are not yet compatible with rails5. So I have been patching them. You will need to grab your own copy of these gems and "patch" them by hand.  You can find the modified files for the below in the sandbox folder.

* ransack
* actionpack
* sass-rails
* rails-observers

I am working to fix the remaining issues this week and next. As of right now ffcrm will run on rails5.

**Comment by panigrah** [comment]
@JorgeDDW @dan-klasson https://github.com/triloch/fat_free_crm is now passing all tests and on rails5. There are three dependencies that are still broken - but you can fix by patching the relevant files. 

* actionpack - this fix is only required for passing tests - it is not required for production. waiting on this fix https://github.com/rails/rails/issues/26569
* rails-observers - waiting on this fix. https://github.com/rails/rails-observers/pull/41
* sass-rails - waiting on this fix. https://github.com/rails/sass-rails/issues/376

Let me know if you need detailed steps to get going on R5.
